import axios from 'axios';
import type { Form, FormSubmission } from '../types/form';
import { mockForms, mockSubmissions } from '../utils/mockData';

const API = axios.create({
  baseURL: 'http://localhost:5000/api/forms',
});

const delay = (ms: number) =>
  new Promise((resolve) => setTimeout(resolve, ms));

export const formService = {
  async getAllForms(): Promise<Form[]> {
  const token = localStorage.getItem('token');

  if (!token) {
    throw new Error('Authentication token not found');
  }

  const response = await API.get('/my-forms', {
    headers: {
      Authorization: `Bearer ${token}`,
    },
  });

  const backendForms = response.data.data || [];

  return backendForms.map((form: any): Form => ({
    id: form._id,
    title: form.title,
    description: form.description || '',
    status: 'draft',
    questions: [],
    theme: {
      primaryColor: '#6366f1',
      backgroundColor: '#020617',
      cardStyle: 'glass',
      borderRadius: 'md',
      fontFamily: 'Inter',
    },
    settings: {
      allowAnonymous: true,
      collectEmail: true,
      limitOneResponse: false,
      showProgressBar: true,
      customSuccessMessage: 'Thank you for your submission!',
    },
    createdAt: form.createdAt,
    updatedAt: form.updatedAt,
    responsesCount: form.submissions || 0,
    completionRate: 0,
    viewsCount: 0,
    slug: form.title
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, ''),
  }));
},

  async getFormById(id: string): Promise<Form | null> {
    await delay(200);
    return mockForms.find((f) => f.id === id || f.slug === id) || null;
  },

  async generateFormWithAI(prompt: string): Promise<Form> {
    await delay(1500); // Simulates backend processing time
    const generatedForm: Form = {
      id: `form_${Date.now()}`,
      slug: `ai-gen-${Date.now()}`,
      title: prompt.length > 40 ? `${prompt.substring(0, 40)}...` : prompt,
      description: 'Intelligently generated by Forma AI Engine.',
      status: 'draft',
      createdAt: new Date().toISOString().split('T')[0],
      updatedAt: new Date().toISOString().split('T')[0],
      responsesCount: 0,
      viewsCount: 0,
      completionRate: 0,
      theme: {
        primaryColor: '#8b5cf6',
        backgroundColor: '#020617',
        cardStyle: 'glass',
        borderRadius: 'md',
        fontFamily: 'Inter',
      },
      settings: {
        allowAnonymous: true,
        collectEmail: true,
        limitOneResponse: false,
        showProgressBar: true,
        customSuccessMessage: 'Thank you for your submission!',
      },
      questions: [
        {
          id: `q_${Date.now()}_1`,
          type: 'short_text',
          title: 'Full Name',
          placeholder: 'John Doe',
          order: 1,
          validation: { required: true },
        },
        {
          id: `q_${Date.now()}_2`,
          type: 'dropdown',
          title: 'Primary Goal',
          order: 2,
          options: [
            { id: 'o1', label: 'Business Acceleration', value: 'business' },
            { id: 'o2', label: 'Academic Study', value: 'academic' },
            { id: 'o3', label: 'Personal Project', value: 'personal' },
          ],
          validation: { required: true },
        },
        {
          id: `q_${Date.now()}_3`,
          type: 'rating',
          title: 'Satisfaction Level',
          order: 3,
          validation: { required: true, min: 1, max: 5 },
        },
      ],
    };
    mockForms.unshift(generatedForm);
    return generatedForm;
  },

  async getFormResponses(formId: string): Promise<FormSubmission[]> {
    await delay(250);
    return mockSubmissions.filter((s) => s.formId === formId);
  },

  async submitFormResponse(formId: string, answers: Record<string, any>): Promise<boolean> {
    await delay(350);
    const newSubmission: FormSubmission = {
      id: `sub_${Date.now()}`,
      formId,
      submittedAt: new Date().toISOString(),
      completionTimeSeconds: 45,
      device: 'desktop',
      answers,
    };
    mockSubmissions.unshift(newSubmission);
    return true;
  },
};